### ISSUE TITLE
想问一下search方法是否有错误，没有学过md语法，抱歉

### ISSUE THREAD

**Issue by glory6ms** [Morgan279/R-Tree#1]
`public boolean isIntersect(Bound bound) {
        return this.getLowerBound() > bound.getHigherBound()
                || this.getHigherBound() < bound.getLowerBound();
    }`
     这儿是排除了两类边界不想交点情况，如果边界有重叠，这里和isOverlap都会返回false,但是在search方法里面，如果isOverlap是false结果就返回空
`public <T> void search(Rectangle searchRectangle, RTreeNode<T> rootNode, Set<RTreeEntry<T>> resultSet) {
            //pruning directly if the node's rectangle does not overlap the search rectangle
            if (!searchRectangle.isOverlap(rootNode.getRectangle())) return;
            // 挨个遍历
            for (RTreeEntry<T> entry : rootNode.getEntries()) {
    
                if (!searchRectangle.isOverlap(entry.getRectangle())) continue;
    
                if (rootNode.isLeafNode()) {
                    resultSet.add(entry);
                } else {
                    search(searchRectangle, entry.getChildren(), resultSet);
                }
            }
        }`
    
   是否应该改为 if (searchRectangle.isOverlap(rootNode.getRectangle())) ，不然得到的是完全不相交的RTreeEntry，

**Comment by Morgan279** [comment]
`if (!searchRectangle.isOverlap(entry.getRectangle())) continue;`
This statement means if  search rectangle is not overlap with the entry's rectangle, then ignore it and go next so that the entry will be pruned.
